---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/api/v1/query_range?end=1508842990&query=sum(container_cpu_usage_seconds_total%7Bcontainer_name=%22registry%22,job=%22kubernetes-cadvisor%22%7D)%20*%201e9&start=1508842770&step=20s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer theToken
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '425'
      Content-Type:
      - application/json
      Date:
      - Tue, 24 Oct 2017 14:22:14 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=292825d0933e3f4a6179fd077c4f6c17; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1508842770,"15728440689"],[1508842790,"15728440689"],[1508842810,"15728440689"],[1508842830,"15728440689"],[1508842850,"15728440689"],[1508842870,"15728440689"],[1508842890,"15728440689"],[1508842910,"15964088028"],[1508842930,"15964088028"],[1508842950,"15964088028"],[1508842970,"16048981383.999998"],[1508842990,"16048981383.999998"]]}]}}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 14:22:14 GMT
- request:
    method: get
    uri: https://capture.context.com/api/v1/query_range?end=1508842990&query=sum(container_memory_usage_bytes%7Bcontainer_name=%22registry%22,job=%22kubernetes-cadvisor%22%7D)&start=1508842770&step=20s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer theToken
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '375'
      Content-Type:
      - application/json
      Date:
      - Tue, 24 Oct 2017 14:22:14 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=292825d0933e3f4a6179fd077c4f6c17; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1508842770,"19456000"],[1508842790,"19456000"],[1508842810,"19456000"],[1508842830,"19456000"],[1508842850,"19456000"],[1508842870,"19456000"],[1508842890,"19456000"],[1508842910,"88653824"],[1508842930,"88653824"],[1508842950,"88653824"],[1508842970,"35565568"],[1508842990,"35565568"]]}]}}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 14:22:14 GMT
recorded_with: VCR 3.0.3
