---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/api/v1/query_range?end=1508842990&query=sum(container_cpu_usage_seconds_total%7Bcontainer_name=%22%22,id=%22/%22,instance=%22capture.context.com%22,job=%22kubernetes-cadvisor%22%7D)%20*%201e9&start=1508842770&step=20s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer theToken
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '455'
      Content-Type:
      - application/json
      Date:
      - Tue, 24 Oct 2017 14:22:15 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=292825d0933e3f4a6179fd077c4f6c17; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1508842770,"5099340804365.001"],[1508842790,"5099340804365.001"],[1508842810,"5099340804365.001"],[1508842830,"5099340804365.001"],[1508842850,"5099340804365.001"],[1508842870,"5099340804365.001"],[1508842890,"5099340804365.001"],[1508842910,"57136598799"],[1508842930,"57136598799"],[1508842950,"57136598799"],[1508842970,"234114672990"],[1508842990,"234114672990"]]}]}}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 14:22:15 GMT
- request:
    method: get
    uri: https://capture.context.com/api/v1/query_range?end=1508842990&query=sum(container_memory_usage_bytes%7Bcontainer_name=%22%22,id=%22/%22,instance=%22capture.context.com%22,job=%22kubernetes-cadvisor%22%7D)&start=1508842770&step=20s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer theToken
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '399'
      Content-Type:
      - application/json
      Date:
      - Tue, 24 Oct 2017 14:22:15 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=292825d0933e3f4a6179fd077c4f6c17; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1508842770,"3560779776"],[1508842790,"3560779776"],[1508842810,"3560779776"],[1508842830,"3560779776"],[1508842850,"3560779776"],[1508842870,"3560779776"],[1508842890,"3560779776"],[1508842910,"2368126976"],[1508842930,"2368126976"],[1508842950,"2368126976"],[1508842970,"3614674944"],[1508842990,"3614674944"]]}]}}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 14:22:15 GMT
- request:
    method: get
    uri: https://capture.context.com/api/v1/query_range?end=1508842990&query=sum(container_network_transmit_bytes_total%7Bcontainer_name=%22%22,id=%22/%22,instance=%22capture.context.com%22,job=%22kubernetes-cadvisor%22,interface=~%22eth.*%22%7D)&start=1508842770&step=20s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer theToken
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '353'
      Content-Type:
      - application/json
      Date:
      - Tue, 24 Oct 2017 14:22:15 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=292825d0933e3f4a6179fd077c4f6c17; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1508842770,"1039907"],[1508842790,"1039907"],[1508842810,"1039907"],[1508842830,"1039907"],[1508842850,"1039907"],[1508842870,"1039907"],[1508842890,"1039907"],[1508842910,"38263"],[1508842930,"38263"],[1508842950,"38263"],[1508842970,"64791"],[1508842990,"64791"]]}]}}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 14:22:15 GMT
- request:
    method: get
    uri: https://capture.context.com/api/v1/query_range?end=1508842990&query=sum(container_network_receive_bytes_total%7Bcontainer_name=%22%22,id=%22/%22,instance=%22capture.context.com%22,job=%22kubernetes-cadvisor%22,interface=~%22eth.*%22%7D)&start=1508842770&step=20s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer theToken
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '358'
      Content-Type:
      - application/json
      Date:
      - Tue, 24 Oct 2017 14:22:15 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=292825d0933e3f4a6179fd077c4f6c17; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1508842770,"4338291"],[1508842790,"4338291"],[1508842810,"4338291"],[1508842830,"4338291"],[1508842850,"4338291"],[1508842870,"4338291"],[1508842890,"4338291"],[1508842910,"131674"],[1508842930,"131674"],[1508842950,"131674"],[1508842970,"257318"],[1508842990,"257318"]]}]}}'
    http_version: 
  recorded_at: Tue, 24 Oct 2017 14:22:15 GMT
recorded_with: VCR 3.0.3
