---
:ems:
  :ems_kubernetes:
    :event_handling:
      :event_groups:
:http_proxy:
  :kubernetes:
    :host:
    :password:
    :port:
    :user:
:container_scanning:
  :scanning_job_timeout: 20.minutes
